### ISSUE TITLE
Investigate vocabulary mismatch in train_artm

### ISSUE THREAD

**Issue by m09** [src-d/tm-experiments#21]
In `train_artm.py`, when using CF data, `doctopic.shape[0]` (the number of documents in the ARTM theta matrix) is different from the number of documents reported from `docword_input_path` or `doc_names`.

The current fix is to save the new index (from the ARTM model) and use it in later operations. The places in the code related to this bug and its workaround are marked with a `# TODO(https://github.com/src-d/tm-experiments/issues/21)` for easy grepping.

**Comment by r0mainK** [comment]
Okay, so I investigated this during the past hour or so. 

The first thing I saw was that it might be linked to a forgotten arg passed when retrieving the theta matrix. That was not it, although it should not have been there.

Next, I tried to see how the number of documents decreases. It turns out is was pretty random. The number would not decrease after the first iteration, but after it would, then go back up, etc, as if it was random. I noticed at that point that I had omitted to set the parameter `reuse_theta` to `True` when create the ARTM model. Doing so resulted in two things:

- an important increase in performance (I did not train the model until the end, but it was quite noticeable on CF data, at least on a metrics PoV). I will let the training go on and report here to see how the model differs from the one Hugo created for the demo, but ended being of poor quality at first sight.
- a stagnation of the number of documents being removed. To be precise, out of the initial 59818 documents, past the first iteration only 59816 remained - but the number did not vary anymore.

At this point I checked whether:

- the number of documents we were displaying initially was wrong. That was not the case.
- there were documents which were empty but had not been removed, or possibly had negative counts somehow. That was not the case.

So it seemed the problem came from BigARTM. I then looked more in depth into the 2 documents being removed. I found that:
- it was systematically the same documents.
- it was systematically the last 2 documents, i.e. documents indexed 59816 and 59817.

I tried modifying the batch size, to see if that changed anything, It did not. I then added an artificial document, with just a single word with count 1. Guess what: 2 documents were still being removed, the one indexed 59817, and the artificial document 59818. 

So _it seems_ there might be a bug in BigARTM. Going to look into this a bit more, but if I don't find anything I think I will push a new temporary fix, and raise an issue for the guys at BigARTM to take care of.

**Comment by m09** [comment]
Great :male_detective: work @r0mainK, thanks! Please reference this issue if you end up raising one in BigARTM so that we have a link here :)

**Comment by r0mainK** [comment]
Okay so I messed up a bit while investigating. Actually, it is not the last documents of the index that disappear.  However, it does seem to be systematically the same being removed, even when adding artificial counts. It turns out for CF the correct document where actually at indexes 29328 and 25638, which respectively have 2 and 1 total word count.

So this is actually a bug that it seems to be affecting lower counts - which explains why when doing tests on smaller datasets, the amount of documents removed is much higher, sometimes leading to all documents being deleted on very small corpuses. I noted that these where not the only documents with very low counts though, for instance in CF we have 486 documents with total word count of 1, and 290 with total word count of 2. I am going to try a couple more things, I think we might be able to fix this somehow by _hacking the mainframe_ but in all cases the conclusion is the same: BigARTM is bugged.

**Comment by r0mainK** [comment]
So, after some testing and looking around the API doc, I found that we could store the `theta` matrix as a `phi` matrix, by providing an argument to the ARTM constructor (`theta_name`).  The main difference is that we can get the matrix directly in dense form, rather then in sparse form to be converted afterwards.

It seems that when doing this, the bug disappears - so we will be switching to this workaround. Regarding the bug itself, this leads me to think there is a problem in the `get_theta_sparse` method, and possibly the `get_phi_sparse` method as well - if they are implemented the same - although I have not tested the latter. This is supported by the fact that the documents that disappeared had very small counts, as indicated previously, but also that in some cases the number of documents increased back, indicating the data was not lost. In all cases I suspect there must be some issue with the sparsity. 

Anyway, going to close this issue once the PR is merged and open one in BigARTM linking here.
